name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Send APK to Telegram
      env:
        TELEGRAM_BOT_TOKEN: 8034267278:AAGUWCyTEAK_ub3Sk9AOtz9mQ1Ihl6Ukxh8
        CHAT_ID: 7663483746
      run: |
        curl -F document=@app/build/outputs/apk/release/app-release.apk \
          "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}&caption=האפליקציה מוכנה להורדה!"
