name: Android APK Build

on:
  push:
    branches:
      - main  # כל פעם שיש commit ל-main יתחיל תהליך הבנייה

jobs:
  build:
    runs-on: ubuntu-latest  # הריצה תתבצע על מערכת אובונטו

    steps:
      # צעד ראשון: להוריד את הריפוזיטורי שלך
      - name: Checkout repository
        uses: actions/checkout@v2

      # צעד שני: להוריד ולהתקין את Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # בחרנו את גרסת ה-JDK

      # צעד שלישי: נפרק את ה־keystore שהעלינו כ־secret ונשמור אותו כקובץ בשם release.keystore
      - name: Decode keystore from secret
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release.keystore

      # צעד רביעי: הרצת פקודת gradle כדי לבנות את ה־APK
      - name: Build the APK
        run: ./gradlew assembleRelease  # אם יש בעיה בהגדרת הפקודה תוכל להוסיף נתיב למיקום הגראדל